services:
  chromium:
    image: lscr.io/linuxserver/chromium:latest
    container_name: remote-chromium
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: Europe/Berlin
      LC_ALL: de_DE.UTF-8
    volumes:
      - ./config:/config
    ports:
      - "127.0.0.1:3000:3000"
      - "127.0.0.1:3001:3001"
    shm_size: 1gb
    restart: unless-stopped
